name = "register"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-06-23"
[vars]
MY_NAME = "example_dev_token"

[env.dev]
name = "register-dev"
kv_namespaces = [
         { binding = "TESTKV", preview_id = "29fb42e8b5fe42fdbeeb116cbddc9897", id = "bab549ec50a24dd497ab7ab27241ff24" }
]
[env.dev.vars]
MY_NAME = "blurryface"
